### ISSUE TITLE
setup.py requires Python version <3.7

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/hca-metadata-api#20]
See: https://github.com/DataBiosphere/hca-metadata-api/blob/master/setup.py#L8

Azul uses Python 3.8 and we depend on this repo, therefore I think we should remove this requirement, and that it is likely safe to do so.

**Comment by melainalegaspi** [comment]
The line in question limits the dependency on data classes to versions of python<3.7 this works as intended
