### ISSUE TITLE
Unit tests fail because DSS is EOL

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/hca-metadata-api#37]
https://travis-ci.com/github/DataBiosphere/hca-metadata-api/builds/219572803

**Comment by noah-aviel-dove** [comment]
https://travis-ci.com/github/DataBiosphere/hca-metadata-api/builds/219572803

**Comment by dsotirho-ucsc** [comment]
Freebie of https://github.com/DataBiosphere/hca-metadata-api/issues/38 (PR https://github.com/DataBiosphere/hca-metadata-api/pull/42)
