### ISSUE TITLE
Add support for schema version '3.0.0' of 'links'

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/hca-metadata-api#39]
Add support for the upcoming version `3.0.0` of `links`, currently on metadata-schema's staging environment https://schema.staging.data.humancellatlas.org/system/3.0.0/links and referenced by the files in the canned staging area https://github.com/HumanCellAtlas/schema-test-data/tree/release-data-26/03/2021/tests/links

**Comment by melainalegaspi** [comment]
@danielsotirhos to create PR for #38 and make this a freebie of that PR.

**Comment by dsotirho-ucsc** [comment]
Freebie of https://github.com/DataBiosphere/hca-metadata-api/issues/38 (PR https://github.com/DataBiosphere/hca-metadata-api/pull/42)
