### ISSUE TITLE
Fix test cases by using bundles from production

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/hca-metadata-api#7]
The following test cases currently fail because they are attempting to use bundles on staging that are no longer available. Fix these test cases by using equivalent bundles from production.

test/test.py
- test_vx_primary_cs_bundle()
- test_vx_analysis_cs_bundle()
- test_vx_analysis_specimen_bundle()

**Comment by melainalegaspi** [comment]
This was relevant for DCP1, not DCP2.
